services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    
  db:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    volumes:
      - timeseries_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: db

volumes:
  timeseries_data: