services:

  web_service:
    build: services/web
    ports:
      - "8000:8000"
    volumes:
      - ./services/web:/web
      - ./logger.py:/web/logger.py

  moex_service:
    build: services/moex
    ports:
      - "8001:8001"
    volumes:
      - ./services/moex:/moex
      - ./logger.py:/moex/logger.py

  db:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    volumes:
      - timeseries_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: db

  db_service:
    build: services/db
    ports:
      - "8002:8002"
    volumes:
      - ./services/db:/db_service
      - ./logger.py:/db_service/logger.py
    depends_on:
      - db

  updater_service:
    build: services/updater
    ports:
      - "8003:8003"
    volumes:
      - ./services/updater:/updater
      - ./logger.py:/updater/logger.py
    depends_on:
      - moex_service
      - db_service

volumes:
  timeseries_data:
