services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:5050"
    volumes:
      - .:/app
    
  db:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5432:5432"
    volumes:
      - timeseries_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: db

  data_updater:
    build:
      context: .
      dockerfile: data_updater/Dockerfile
    volumes:
      - .:/data_updater

volumes:
  timeseries_data: